package com.mercymayagames.taskr.ui.main

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.fragment.app.Fragment
import com.mercymayagames.taskr.R
import com.mercymayagames.taskr.databinding.ActivityMainBinding
import com.mercymayagames.taskr.ui.main.fragments.CompletedTasksFragment
import com.mercymayagames.taskr.ui.main.fragments.SettingsFragment
import com.mercymayagames.taskr.ui.main.fragments.TasksFragment
import com.google.android.material.bottomnavigation.BottomNavigationView

/**
 * In the following lines, we set up the main activity which hosts the bottom navigation bar.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Using ViewBinding generated by 'viewBinding true' config
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        loadFragment(TasksFragment())

        binding.bottomNav.setOnNavigationItemSelectedListener { menuItem ->
            when (menuItem.itemId) {
                R.id.nav_tasks -> {
                    loadFragment(TasksFragment())
                    true
                }
                R.id.nav_completed -> {
                    loadFragment(CompletedTasksFragment())
                    true
                }
                R.id.nav_settings -> {
                    loadFragment(SettingsFragment())
                    true
                }
                else -> false
            }
        }
    }

    private fun loadFragment(fragment: Fragment) {
        // Replace the container with the fragment
        supportFragmentManager.beginTransaction()
            .replace(R.id.fragmentContainer, fragment)
            .commit()
    }
}
